.\"             -*-Nroff-*-
.\"
.TH "o" 1 "28 Jun 2020" "" ""
.SH NAME
o \- a webserver
.sp
THIS MAN PAGE IS A WORK IN PROGRESS, AND IS INCOMPLETE
.SH SYNOPSIS
.B algernon
file or directory
.sp
.SH DESCRIPTION
Serve a file or directory
.sp
.SH OPTIONS
.sp
.TP
.B \-v or\-\-version
displays the current version number
.TP
.B \-h or \-\-help
displays brief usage information
.PP
.SH "ENV"
.sp
The \fBNO_COLOR\fP environment variable can be set to 1 to disable all colors.
.sp
.SH "WHY"
.sp
Web development with few dependencies and a decent caching system.
.SH "SEE ALSO"
.BR caddy (1)
.BR nginx (1)
.SH BUGS
Only unknown bugs so far.
.SH VERSION
1.12.8
.SH AUTHOR
.B algernon
was written by  Alexander F. Rødseth <xyproto@archlinux.org>
