# Containerfile for making Algernon serve HTTP on port 80 and HTTPS+HTTP/2 on port 443
FROM golang:1.26-alpine as gobuilder
LABEL maintainer="Alexander F. Rødseth <xyproto@archlinux.org>"

COPY . /algernon
WORKDIR /algernon

# GOARCH is inherited from the build platform (native amd64 / aarch64 builds).
RUN GOOS=linux \
    CGO_ENABLED=0 \
    go build \
      -mod=vendor \
      -a \
      -trimpath \
      -installsuffix cgo \
      -ldflags="-w -s" \
      -o /bin/algernon

RUN apk add upx && upx /bin/algernon

FROM scratch
COPY --from=gobuilder /bin/algernon /bin/algernon
COPY --from=gobuilder /tmp /tmp
VOLUME /srv/algernon
VOLUME /etc/algernon
WORKDIR /srv/algernon

EXPOSE 80 443

ENTRYPOINT ["/bin/algernon", "-c", "--domain", "--noninteractive", "--cachesize", "67108864", "--prod", "--cert", "/etc/algernon/cert.pem", "--key", "/etc/algernon/key.pem", "/srv/algernon"]
